[Telegram]
    [Telegram.BOT]
        API_ID       = ""
        API_HASH     = ""
        BOT_TOKEN    = ""

    [Telegram.USER]
        API_ID       = ""
        API_HASH     = ""
        PHONE_NUMBER = ""


[Database]
    [Database.SQL]
        URI          = ""
        HOST         = ""
        PORT         = 
        USER         = ""
        PASSWORD     = ""
        DATABASE     = ""

    [Database.REDIS]
        URI          = ""
        HOST         = ""
        PORT         = 
        USER         = ""
        PASSWORD     = ""


[Teloxide]
    WORKDIR        = "KWorkdir"
    SESSION_NAME   = "KissShot_BotClient"
    WORKERS        = 10
    PLUGINS_DIR    = "KPlugins"
    PARSE_MODE     = "HTML"
    TIMEOUT        = 30
    REQUEST_CONCURRENCY = 100
    MAX_NETWORK_RETRIES = 3
    API_URL        = ""
    LOGGING        = true


[Config]
    [Config.BASIC]
        ADMIN        = [766109755]
        CHANNEL      = "heckervault"
        GROUP        = "heckervaultchat"

    [Config.LIMITS]
        MAX_CC_SCR   = 3001
        MAX_SK_SCR   = 3001
        MAX_CC_CHK   = 5
        MAX_SK_CHK   = 20

    [Config.REGEX]
        CC_REGEX     = '[0-9]{16}[|][0-9]{1,2}[|][0-9]{2,4}[|][0-9]{3}'
        SK_REGEX     = 'sk_live_\\S+'
        BIN_REGEX    = '^[0-9]{16}$'

    [Config.GIFT_CODE]
        PREFIX       = "HeckerVault_"

    [Config.PROXY]
        PROXY        = ""

    [Config.DEFAULT_USER_VALUE]
        ANTISPAM = 30
        BALANCE = 0
        STATUS = "FREE"
